#~/.dein_lazy.toml

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/vimfiler.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'


[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'kannokanno/previm'


[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'junegunn/vim-easy-align'
[[plugins]]
repo = 'mattn/emmet-vim'


[[plugins]]
repo = 'mattn/sonictemplate-vim'
